### ISSUE TITLE
Refined GitHub has been loaded twice.

### ISSUE THREAD

**Issue by RussKie** [refined-github/refined-github#4827]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

I haven't found an exact set of steps that leads to the message, but generally a combination of viewing all files in a PR on GitHub, viewing files for a specific commit result in the warning in the logs.
Sometimes I get `TypeError: Cannot read properties of undefined (reading 'cloneNode')` error first, then after switching between tabs I eventually get the warning. Sometimes I get the warning straight away, followed by the error...

### Screenshot

![image](https://user-images.githubusercontent.com/4403806/135013548-ff189318-630f-4cd5-a656-1862cec2e2a6.png)

### Console errors

```shell
VM52 refined-github.js:8646 
Uncaught TypeError: Cannot read properties of undefined (reading 'cloneNode')
    at add (VM52 refined-github.js:8646)
    at runAdd (VM52 refined-github.js:4602)
    at applyChanges (VM52 refined-github.js:4572)
    at SelectorObserver.addRootNodes (VM52 refined-github.js:4724)
    at Array.processBatchQueue (VM52 refined-github.js:4544)
    at MutationObserver.handleMutations (VM52 refined-github.js:4561)
add @ VM52 refined-github.js:8646
runAdd @ VM52 refined-github.js:4602
applyChanges @ VM52 refined-github.js:4572
addRootNodes @ VM52 refined-github.js:4724
processBatchQueue @ VM52 refined-github.js:4544
handleMutations @ VM52 refined-github.js:4561
setTimeout (async)
handleMutations @ VM52 refined-github.js:4563
attributes (async)
scheduleMacroTask @ VM52 refined-github.js:4555
(anonymous) @ VM52 refined-github.js:4548
SelectorObserver.observe @ VM52 refined-github.js:4761
observe @ VM52 refined-github.js:4781
init @ VM52 refined-github.js:8642
async function (async)
init @ VM52 refined-github.js:8631
runFeature @ VM52 refined-github.js:1964
setupPageLoad @ VM52 refined-github.js:1977
add @ VM52 refined-github.js:1999
async function (async)
add @ VM52 refined-github.js:1984
(anonymous) @ VM52 refined-github.js:8626
(anonymous) @ VM52 refined-github.js:9712
(anonymous) @ VM52 refined-github.js:9713
```

### Example URL

https://github.com/dotnet/winforms/pull/5842/commits/d9fd5007c144dcaebe7314a4036cd0e0540e37e3

### Browser(s) used

Edge, version 94.0.992.31 (Official build) (64-bit)
Extension, v21.9.18

**Comment by graemechapman** [comment]
I've been seeing similar when opening a PR and then going to the `Files Changed` tab. Also when this happens I don't seem to get the quick review buttons. Refreshing the page fixes it.

**Comment by kidonng** [comment]
> Also when this happens I don't seem to get the quick review buttons. Refreshing the page fixes it.

That's #4702

**Comment by yakov116** [comment]
I am having this on the latest release. I cannot figure out when it happens. But after sometime of having a tab open it triggers.

**Comment by adrianschmidt** [comment]
I get this error all the time, and have been for at least a few days, but I suspect for a longer time, because I've been noticing that GitHub pages I've had open in a tab for an extended period of time get really slow (I first noticed it on our team's project board that I have pinned, so it stays open for weeks and I occasionally refresh it manually, or restart the browser). Last week it was getting really slow to load when I switched to it from another browser tab after the project tab had not been active for a while (a few minutes at least, but sometimes hours). The problem went away when I refreshed the page, but got worse so quickly that I noticed it taking seconds to load again already later the same day. That's when I open the dev-tools and noticed copious amounts of the message about Refined GitHub having been loaded twice.

The following screenshot is from a page I refreshed just before starting to write this comment, so, I'm not sure, but maybe 5-10 minutes ago (I've switched to it a few times, and once or twice I noticed that a new warning was logged to the console just after I switched to that tab):

![image](https://user-images.githubusercontent.com/154725/139659684-10eca9dd-bcf6-4e09-80f7-2c8849f5e563.png)

Chrome says I'm using version 21.10.25 of the plugin, which is the latest one released at the time of writing. I noticed just now that there's been no new release since this issue was closed, so hopefully it's fixed, but since I've written up the comment anyway, I guess I'll post it in case the problem turns out not to be fixed and this can be of any help 🙂

**Comment by fregante** [comment]
Thanks for the report. 

I did see some duplicate injection of the CSS file, but I never see that message. 

The new release is out today: 21.11.1

Let me know if you still see it.

**Comment by fregante** [comment]
I think I found the bug: https://github.com/fregante/content-scripts-register-polyfill/issues/48

It was caused by the combination of:

- https://github.com/fregante/webext-dynamic-content-scripts/pull/24
- https://github.com/refined-github/refined-github/commit/bee7c5fdf5273b495193ba2f2fde40a8b0da5b3c#diff-7277d16641a1f5dbb16de8f89fde78eaff2c5a0b9d20bd4ea5296e9dd4fb9f63

**Comment by adrianschmidt** [comment]
I plan to look into the underlying issue and see if it's within my capacity to resolve it, but I simply haven't had the possibility to prioritise taking the time to do it. It's top of my personal agenda though (just not my job agenda, unfortunately 😞).

**Comment by KaelWD** [comment]
@adrianschmidt are you also seeing a huge memory leak on pages left open for a couple of days? 
It doesn't show up in a heap snapshot but task manager shows 500MB+ for each tab after just 24 hours, and I've seen multiple GB if left for longer. It only happens with the extension enabled and if I check the console afterwards there's this warning repeated hundreds of times.

**Comment by adrianschmidt** [comment]
@KaelWD I haven't checked, and I've disabled the add-on for now, because it's been giving me too much trouble. But I'd guess I'd see the same thing.

**Comment by fregante** [comment]
This has been fixed in https://github.com/refined-github/refined-github/pull/5180 thanks to https://github.com/fregante/webext-dynamic-content-scripts/pull/30

However the fix only applies to GitHub.com and not GH Enterprise users.

We'll likely release a new version on Sunday, 21.12.12

**Comment by kidonng** [comment]
Saw this review on Chrome Web Store:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/44045911/153753893-77abe59e-fea4-4bcd-9eb6-96b156168253.png">

Not sure what's that about but I do feel the problem persists to some extent.
