### ISSUE TITLE
The hotfix expires too soon

### ISSUE THREAD

**Issue by vedangwartikar** [refined-github/refined-github#4861]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

GitHub feed showing weird white-colored panel in the middle. I'm using Brave browser with dark mode enabled.

### Screenshot

Without extension (default): 

![image](https://user-images.githubusercontent.com/43764240/135756365-429d92b8-fef1-4ff4-a8dd-bf0408af189a.png)

With extension: 

![image](https://user-images.githubusercontent.com/43764240/135756238-1f21e42b-51d6-4011-8632-c7a217dc5c35.png)

### Example URL

https://github.com/

### Browser(s) used

Brave (Chromium-based)

**Comment by cheap-glitch** [comment]
I think this was fixed in https://github.com/sindresorhus/refined-github/pull/4842. It doesn't seem to have made it into the latest release, so you'll have to wait for the next one.

**Comment by fregante** [comment]
@cheap-glitch Apparently the hotfix functionality doesn't work all the time, which I think is due to a too-early expiration:

1. User opens GitHub
2. Shown without hotfix
3. Hotfix downloads
4. User opens GitHub the next day
5. Hotfix is in cache but expired, so buggy feature is still shown


This is a meta bug we should look into

**Comment by cheap-glitch** [comment]
> 5. Hotfix is in cache but expired, so buggy feature is still shown

Does that mean the hotfix just needs to downloaded again? In that case, wouldn't reloading the page or navigating without ajax apply the hotfix properly?

**Comment by fregante** [comment]
There's a `staleWhileRevalidate` option that should return the hotfix even after it expired, as long as it's long enough. If it's past both the maxAge and staleWhileRevalidate date then it will return `undefined`
